# 1. Preparación de los datos

In [39]:
import pandas as pd

In [40]:
df = pd.read_csv('./dataset/CovidData.csv')
print(len(df))
df.head()

1048575

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97

In [41]:
df.dtypes

USMER                    int64
MEDICAL_UNIT             int64
SEX                      int64
PATIENT_TYPE             int64
DATE_DIED               object
INTUBED                  int64
PNEUMONIA                int64
AGE                      int64
PREGNANT                 int64
DIABETES                 int64
COPD                     int64
ASTHMA                   int64
INMSUPR                  int64
HIPERTENSION             int64
OTHER_DISEASE            int64
CARDIOVASCULAR           int64
OBESITY                  int64
RENAL_CHRONIC            int64
TOBACCO                  int64
CLASIFFICATION_FINAL     int64
ICU                      int64
dtype: object

In [42]:
clasiffication_final = pd.to_numeric(df.CLASIFFICATION_FINAL, errors='coerce')


df.CLASIFFICATION_FINAL = pd.to_numeric(df.CLASIFFICATION_FINAL, errors='coerce')


df.CLASIFFICATION_FINAL = df.CLASIFFICATION_FINAL.fillna(0)


df[clasiffication_final.notnull()][['USMER', 'CLASIFFICATION_FINAL']]

         USMER  CLASIFFICATION_FINAL
0            2                     3
1            2                     5
2            2                     3
3            2                     7
4            2                     3
...        ...                   ...
1048570      2                     7
1048571      1                     7
1048572      2                     7
1048573      2                     7
1048574      2                     7

[1048575 rows x 2 columns]

In [43]:
replacer = lambda str: str.lower().str.replace(' ', '_')
df.columns = replacer(df.columns.str)
for col in list(df.dtypes[df.dtypes == 'object'].index):
    df[col] = replacer(df[col].str)
df.head()

,usmer,medical_unit,sex,patient_type,date_died,intubed,pneumonia,age,pregnant,diabetes,...,asthma,inmsupr,hipertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,clasiffication_final,icu
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97

In [44]:
numerical = ['medical_unit', 'sex', 'patient_type', 'intubed', 'pneumonia', 'age', 'pregnant', 'diabetes', 'copd', 'asthma',
             'inmsupr', 'hipertension', 'other_disease', 'cardiovascular', 'obesity', 'renal_chronic', 'tobacco', 'clasiffication_final']
categorical = ['date_died']
df[numerical].nunique()

medical_unit             13
sex                       2
patient_type              2
intubed                   4
pneumonia                 3
age                     121
pregnant                  4
diabetes                  3
copd                      3
asthma                    3
inmsupr                   3
hipertension              3
other_disease             3
cardiovascular            3
obesity                   3
renal_chronic             3
tobacco                   3
clasiffication_final      7
dtype: int64

In [45]:
from sklearn.model_selection import train_test_split
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=1)

df_train, df_val = train_test_split(df_train_full, test_size=0.33, random_state=1)
y_train = df_train.icu.values
y_val = df_val.icu.values

del df_train['icu']
del df_val['icu']

df_train.head().T

,621053,61377,66591,955159,940355
usmer,1,2,2,2,2
medical_unit,12,4,4,12,12
sex,2,2,1,2,2
patient_type,1,1,2,1,1
date_died,9999-99-99,9999-99-99,9999-99-99,9999-99-99,9999-99-99
intubed,97,97,2,97,97
pneumonia,2,2,2,2,2
age,39,27,48,76,9
pregnant,97,97,2,97,97
diabetes,1,2,2,1,2
copd,2,2,2,2,2
asthma,2,2,2,2,2
inmsupr,2,2,2,2,2
hipertension,1,2,2,2,2
other_disease,2,2,2,2,2
cardiovascular,2,2,2,2,2
obesity,1,2,2,2,2
renal_chronic,2,2,2,2,2
tobacco,2,2,2,2,2
clasiffication_final,3,3,3,7,7

# 2. Análisis de importancia de propiedades

In [46]:
global_mean = df_train_full.icu.mean()
round(global_mean, 3)

79.54

In [48]:
usmer1_mean = df_train_full[df_train_full.usmer == 1].icu.mean()
print(round(usmer1_mean, 3))
usmer2_mean = df_train_full[df_train_full.usmer == 2].icu.mean()
print(round(usmer2_mean, 3))

71.072
84.466

In [49]:
patient1 = df_train_full[df_train_full.patient_type == 1].icu.mean()
print(round(patient1, 3))
patient2 = df_train_full[df_train_full.patient_type == 2].icu.mean()
print(round(patient2, 3))

97.0
5.541

In [50]:
from sklearn.metrics import mutual_info_score

calculate_mi = lambda col: mutual_info_score(col, df_train_full.icu)

df_mi = df_train_full[categorical].apply(calculate_mi)
df_mi = df_mi.sort_values(ascending=False).to_frame(name='mi')
df_mi

                 mi
date_died  0.104314

In [51]:
print(df_train_full[numerical].corrwith(df_train_full.icu))

print(round(df_train_full[df_train_full.medical_unit <= 2].icu.mean(), 3))
print(round(df_train_full[(df_train_full.medical_unit > 3) & 
                          (df_train_full.medical_unit <= 12)].icu.mean(), 3))
print(round(df_train_full[df_train_full.medical_unit > 12].icu.mean(), 3))

print(round(df_train_full[df_train_full.age < 20].icu.mean(), 3))
print(round(df_train_full[(df_train_full.age > 21) & 
                          (df_train_full.age <= 50)].icu.mean(), 3))
print(round(df_train_full[df_train_full.age > 50].icu.mean(), 3))

medical_unit            0.205635
sex                    -0.090943
patient_type           -0.975846
intubed                 0.999429
pneumonia               0.079685
age                    -0.317705
pregnant               -0.089093
diabetes               -0.009432
copd                   -0.019882
asthma                 -0.023839
inmsupr                -0.024258
hipertension           -0.007751
other_disease          -0.035411
cardiovascular         -0.022460
obesity                -0.020571
renal_chronic          -0.019179
tobacco                -0.022483
clasiffication_final    0.193688
dtype: float64
77.846
79.601
73.102
81.445
87.499
60.896

# 3. Ingeniería de propiedades

In [52]:
train_dict = df_train[categorical + numerical].to_dict(orient='records')
dict(sorted(train_dict[0].items()))

{'age': 39,
 'asthma': 2,
 'cardiovascular': 2,
 'clasiffication_final': 3,
 'copd': 2,
 'date_died': '9999-99-99',
 'diabetes': 1,
 'hipertension': 1,
 'inmsupr': 2,
 'intubed': 97,
 'medical_unit': 12,
 'obesity': 1,
 'other_disease': 2,
 'patient_type': 1,
 'pneumonia': 2,
 'pregnant': 97,
 'renal_chronic': 2,
 'sex': 2,
 'tobacco': 2}

In [53]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [54]:
X_train = dv.transform(train_dict)
X_train[0]

array([39.,  2.,  2.,  3.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,
        2., 97., 12.,  1.,  2.,  1.,  2., 97.,  2.,  2.,  2.])

In [55]:
dv.get_feature_names_out()

array(['age', 'asthma', 'cardiovascular', 'clasiffication_final', 'copd',
       'date_died=01/02/2020', 'date_died=01/03/2020',
       'date_died=01/04/2020', 'date_died=01/04/2021',
       'date_died=01/05/2020', 'date_died=01/05/2021',
       'date_died=01/06/2020', 'date_died=01/07/2020',
       'date_died=01/08/2020', 'date_died=01/09/2020',
       'date_died=02/01/2020', 'date_died=02/01/2021',
       'date_died=02/02/2020', 'date_died=02/03/2020',
       'date_died=02/04/2020', 'date_died=02/04/2021',
       'date_died=02/05/2020', 'date_died=02/05/2021',
       'date_died=02/06/2020', 'date_died=02/07/2020',
       'date_died=02/08/2020', 'date_died=02/09/2020',
       'date_died=03/01/2020', 'date_died=03/02/2020',
       'date_died=03/02/2021', 'date_died=03/03/2020',
       'date_died=03/04/2020', 'date_died=03/04/2021',
       'date_died=03/05/2020', 'date_died=03/06/2020',
       'date_died=03/07/2020', 'date_died=03/08/2020',
       'date_died=03/09/2020', 'date_died=04/01/2020',
       'date_died=04/02/2020', 'date_died=04/03/2020',
       'date_died=04/04/2020', 'date_died=04/05/2020',
       'date_died=04/06/2020', 'date_died=04/07/2020',
       'date_died=04/08/2020', 'date_died=04/09/2020',
       'date_died=05/02/2020', 'date_died=05/02/2021',
       'date_died=05/03/2020', 'date_died=05/04/2020',
       'date_died=05/05/2020', 'date_died=05/06/2020',
       'date_died=05/07/2020', 'date_died=05/08/2020',
       'date_died=05/09/2020', 'date_died=05/10/2020',
       'date_died=05/12/2020', 'date_died=06/01/2020',
       'date_died=06/01/2021', 'date_died=06/02/2020',
       'date_died=06/02/2021', 'date_died=06/03/2020',
       'date_died=06/04/2020', 'date_died=06/04/2021',
       'date_died=06/05/2020', 'date_died=06/06/2020',
       'date_died=06/07/2020', 'date_died=06/08/2020',
       'date_died=06/10/2020', 'date_died=06/11/2020',
       'date_died=07/01/2020', 'date_died=07/02/2020',
       'date_died=07/02/2021', 'date_died=07/03/2020',
       'date_died=07/04/2020', 'date_died=07/05/2020',
       'date_died=07/06/2020', 'date_died=07/07/2020',
       'date_died=07/08/2020', 'date_died=07/09/2020',
       'date_died=07/10/2020', 'date_died=07/12/2020',
       'date_died=08/01/2020', 'date_died=08/02/2020',
       'date_died=08/02/2021', 'date_died=08/03/2020',
       'date_died=08/03/2021', 'date_died=08/04/2020',
       'date_died=08/05/2020', 'date_died=08/06/2020',
       'date_died=08/07/2020', 'date_died=08/08/2020',
       'date_died=08/09/2020', 'date_died=08/11/2020',
       'date_died=09/01/2020', 'date_died=09/02/2020',
       'date_died=09/03/2020', 'date_died=09/04/2020',
       'date_died=09/05/2020', 'date_died=09/06/2020',
       'date_died=09/07/2020', 'date_died=09/08/2020',
       'date_died=09/09/2020', 'date_died=10/01/2020',
       'date_died=10/01/2021', 'date_died=10/02/2020',
       'date_died=10/02/2021', 'date_died=10/03/2020',
       'date_died=10/03/2021', 'date_died=10/04/2020',
       'date_died=10/04/2021', 'date_died=10/05/2020',
       'date_died=10/06/2020', 'date_died=10/07/2020',
       'date_died=10/08/2020', 'date_died=10/09/2020',
       'date_died=11/01/2020', 'date_died=11/01/2021',
       'date_died=11/02/2020', 'date_died=11/03/2020',
       'date_died=11/04/2020', 'date_died=11/05/2020',
       'date_died=11/06/2020', 'date_died=11/07/2020',
       'date_died=11/08/2020', 'date_died=11/09/2020',
       'date_died=12/01/2020', 'date_died=12/02/2020',
       'date_died=12/02/2021', 'date_died=12/03/2020',
       'date_died=12/04/2020', 'date_died=12/04/2021',
       'date_died=12/05/2020', 'date_died=12/06/2020',
       'date_died=12/07/2020', 'date_died=12/08/2020',
       'date_died=12/09/2020', 'date_died=12/11/2020',
       'date_died=13/01/2020', 'date_died=13/02/2020',
       'date_died=13/03/2020', 'date_died=13/04/2020',
       'date_died=13/04/2021', 'date_died=13/05/2020',
       'date_died=13/06/2020', 'date_died=13/07/2020',
       'date_died=13/08/2020', 'date_died=13/09/2020',
       'date_died=13/10/2020', 'date_died=14/01/2020',
       'date_died=14/01/2021', 'date_died=14/02/2020',
       'date_died=14/02/2021', 'date_died=14/03/2020',
       'date_died=14/04/2020', 'date_died=14/04/2021',
       'date_died=14/05/2020', 'date_died=14/06/2020',
       'date_died=14/07/2020', 'date_died=14/08/2020',
       'date_died=14/09/2020', 'date_died=14/10/2020',
       'date_died=14/11/2020', 'date_died=15/01/2020',
       'date_died=15/01/2021', 'date_died=15/02/2020',
       'date_died=15/03/2020', 'date_died=15/04/2020',
       'date_died=15/05/2020', 'date_died=15/06/2020',
       'date_died=15/07/2020', 'date_died=15/08/2020',
       'date_died=15/09/2020', 'date_died=15/11/2020',
       'date_died=15/12/2020', 'date_died=16/01/2020',
       'date_died=16/02/2020', 'date_died=16/03/2020',
       'date_died=16/04/2020', 'date_died=16/04/2021',
       'date_died=16/05/2020', 'date_died=16/06/2020',
       'date_died=16/07/2020', 'date_died=16/08/2020',
       'date_died=16/09/2020', 'date_died=16/12/2020',
       'date_died=17/01/2020', 'date_died=17/02/2020',
       'date_died=17/02/2021', 'date_died=17/03/2020',
       'date_died=17/03/2021', 'date_died=17/04/2020',
       'date_died=17/04/2021', 'date_died=17/05/2020',
       'date_died=17/06/2020', 'date_died=17/07/2020',
       'date_died=17/08/2020', 'date_died=17/09/2020',
       'date_died=17/12/2020', 'date_died=18/01/2020',
       'date_died=18/02/2020', 'date_died=18/02/2021',
       'date_died=18/03/2020', 'date_died=18/03/2021',
       'date_died=18/04/2020', 'date_died=18/04/2021',
       'date_died=18/05/2020', 'date_died=18/06/2020',
       'date_died=18/07/2020', 'date_died=18/08/2020',
       'date_died=18/09/2020', 'date_died=18/10/2020',
       'date_died=19/01/2020', 'date_died=19/02/2020',
       'date_died=19/03/2020', 'date_died=19/03/2021',
       'date_died=19/04/2020', 'date_died=19/05/2020',
       'date_died=19/06/2020', 'date_died=19/07/2020',
       'date_died=19/08/2020', 'date_died=19/09/2020',
       'date_died=20/01/2020', 'date_died=20/01/2021',
       'date_died=20/02/2020', 'date_died=20/03/2020',
       'date_died=20/03/2021', 'date_died=20/04/2020',
       'date_died=20/04/2021', 'date_died=20/05/2020',
       'date_died=20/06/2020', 'date_died=20/07/2020',
       'date_died=20/08/2020', 'date_died=20/09/2020',
       'date_died=21/01/2020', 'date_died=21/01/2021',
       'date_died=21/02/2020', 'date_died=21/03/2020',
       'date_died=21/04/2020', 'date_died=21/05/2020',
       'date_died=21/06/2020', 'date_died=21/07/2020',
       'date_died=21/08/2020', 'date_died=21/09/2020',
       'date_died=22/01/2020', 'date_died=22/01/2021',
       'date_died=22/02/2020', 'date_died=22/03/2020',
       'date_died=22/03/2021', 'date_died=22/04/2020',
       'date_died=22/04/2021', 'date_died=22/05/2020',
       'date_died=22/06/2020', 'date_died=22/07/2020',
       'date_died=22/08/2020', 'date_died=22/09/2020',
       'date_died=22/10/2020', 'date_died=22/12/2020',
       'date_died=23/01/2020', 'date_died=23/02/2020',
       'date_died=23/03/2020', 'date_died=23/03/2021',
       'date_died=23/04/2020', 'date_died=23/05/2020',
       'date_died=23/06/2020', 'date_died=23/07/2020',
       'date_died=23/08/2020', 'date_died=23/09/2020',
       'date_died=23/10/2020', 'date_died=23/11/2020',
       'date_died=24/01/2020', 'date_died=24/01/2021',
       'date_died=24/02/2020', 'date_died=24/03/2020',
       'date_died=24/03/2021', 'date_died=24/04/2020',
       'date_died=24/04/2021', 'date_died=24/05/2020',
       'date_died=24/06/2020', 'date_died=24/07/2020',
       'date_died=24/08/2020', 'date_died=24/12/2020',
       'date_died=25/01/2020', 'date_died=25/01/2021',
       'date_died=25/02/2020', 'date_died=25/03/2020',
       'date_died=25/04/2020', 'date_died=25/04/2021',
       'date_died=25/05/2020', 'date_died=25/06/2020',
       'date_died=25/07/2020', 'date_died=25/08/2020',
       'date_died=25/12/2020', 'date_died=26/01/2020',
       'date_died=26/01/2021', 'date_died=26/02/2020',
       'date_died=26/02/2021', 'date_died=26/03/2020',
       'date_died=26/03/2021', 'date_died=26/04/2020',
       'date_died=26/04/2021', 'date_died=26/05/2020',
       'date_died=26/06/2020', 'date_died=26/07/2020',
       'date_died=26/08/2020', 'date_died=26/10/2020',
       'date_died=27/01/2020', 'date_died=27/01/2021',
       'date_died=27/02/2020', 'date_died=27/03/2020',
       'date_died=27/03/2021', 'date_died=27/04/2020',
       'date_died=27/04/2021', 'date_died=27/05/2020',
       'date_died=27/06/2020', 'date_died=27/07/2020',
       'date_died=27/08/2020', 'date_died=27/09/2020',
       'date_died=27/10/2020', 'date_died=27/11/2020',
       'date_died=28/01/2020', 'date_died=28/02/2020',
       'date_died=28/03/2020', 'date_died=28/03/2021',
       'date_died=28/04/2020', 'date_died=28/04/2021',
       'date_died=28/05/2020', 'date_died=28/06/2020',
       'date_died=28/07/2020', 'date_died=28/08/2020',
       'date_died=28/09/2020', 'date_died=28/12/2020',
       'date_died=29/01/2020', 'date_died=29/02/2020',
       'date_died=29/03/2020', 'date_died=29/03/2021',
       'date_died=29/04/2020', 'date_died=29/04/2021',
       'date_died=29/05/2020', 'date_died=29/06/2020',
       'date_died=29/07/2020', 'date_died=29/08/2020',
       'date_died=29/09/2020', 'date_died=30/01/2020',
       'date_died=30/03/2020', 'date_died=30/03/2021',
       'date_died=30/04/2020', 'date_died=30/04/2021',
       'date_died=30/05/2020', 'date_died=30/06/2020',
       'date_died=30/07/2020', 'date_died=30/08/2020',
       'date_died=30/12/2020', 'date_died=31/01/2020',
       'date_died=31/01/2021', 'date_died=31/03/2020',
       'date_died=31/05/2020', 'date_died=31/07/2020',
       'date_died=31/08/2020', 'date_died=31/10/2020',
       'date_died=9999-99-99', 'diabetes', 'hipertension', 'inmsupr',
       'intubed', 'medical_unit', 'obesity', 'other_disease',
       'patient_type', 'pneumonia', 'pregnant', 'renal_chronic', 'sex',
       'tobacco'], dtype=object)

# 4. Entrenamiento del modelo

In [56]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [57]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)
y_pred = model.predict_proba(X_val)
y_pred

array([[2.31097722e-098, 2.28252281e-005, 9.99797731e-001,
        1.79444250e-004],
       [6.31609806e-132, 1.69691510e-003, 8.41653678e-004,
        9.97461431e-001],
       [2.32515099e-098, 2.13119824e-005, 9.99878535e-001,
        1.00153304e-004],
       ...,
       [1.76854323e-098, 3.06534068e-005, 9.99908041e-001,
        6.13051972e-005],
       [5.33812531e-099, 8.31706696e-005, 9.99771252e-001,
        1.45577408e-004],
       [5.02515766e-099, 9.19931442e-005, 9.99851531e-001,
        5.64755831e-005]])

In [58]:
y_pred = model.predict_proba(X_val)[:, 1]
y_pred

array([2.28252281e-05, 1.69691510e-03, 2.13119824e-05, ...,
       3.06534068e-05, 8.31706696e-05, 9.19931442e-05])

In [59]:
churn = y_pred >= 0.5
churn

array([False, False, False, ..., False, False, False])

In [60]:
round((y_val == churn).mean(), 3)

0.017

# 5. Serialización del modelo

In [61]:
import pickle
import joblib

In [62]:
with open('./models/ICU-model.pck', 'wb') as f:
    pickle.dump((dv, model), f)

with open('./models/ICU-model_joblib.pck', 'wb') as f:
    joblib.dump((dv, model), f)

In [63]:
with open('./models/ICU-model.pck', 'rb') as f:
    dv, model = pickle.load(f)
    X_val = dv.transform(val_dict)
    y_pred = model.predict_proba(X_val)

print(y_pred)

with open('./models/ICU-model_joblib.pck', 'rb') as f:
    dv, model = joblib.load(f)
    X_val = dv.transform(val_dict)
    y_pred = model.predict_proba(X_val)

print(y_pred)

[[2.31097722e-098 2.28252281e-005 9.99797731e-001 1.79444250e-004]
 [6.31609806e-132 1.69691510e-003 8.41653678e-004 9.97461431e-001]
 [2.32515099e-098 2.13119824e-005 9.99878535e-001 1.00153304e-004]
 ...
 [1.76854323e-098 3.06534068e-005 9.99908041e-001 6.13051972e-005]
 [5.33812531e-099 8.31706696e-005 9.99771252e-001 1.45577408e-004]
 [5.02515766e-099 9.19931442e-005 9.99851531e-001 5.64755831e-005]]
[[2.31097722e-098 2.28252281e-005 9.99797731e-001 1.79444250e-004]
 [6.31609806e-132 1.69691510e-003 8.41653678e-004 9.97461431e-001]
 [2.32515099e-098 2.13119824e-005 9.99878535e-001 1.00153304e-004]
 ...
 [1.76854323e-098 3.06534068e-005 9.99908041e-001 6.13051972e-005]
 [5.33812531e-099 8.31706696e-005 9.99771252e-001 1.45577408e-004]
 [5.02515766e-099 9.19931442e-005 9.99851531e-001 5.64755831e-005]]

# Pruebas

In [64]:
!curl --request POST 'http://127.0.0.1:8000/predict' \
--header 'Content-Type: application/json' \
--data-raw '{\
    "MEDICAL_UNIT": 1,\
    "SEX": 1,\
    "PATIENT_TYPE": 2,\
    "DATE_DIED: "05/06/2020",\
    "INTUBED": "97",\
    "PNEUMONIA": 2,\
    "AGE": 55,\
    "PREGNANT": 2,\
    "DIABETES": 1,\
    "COPD": 2,\
    "ASTHMA": 2,\
    "INMSUPR": 2,\
    "HIPERTENSION": 1,\
    "OTHER_DISEASE": 2,\
    "CARDIOVASCULAR": 2,\
    "OBESITY": 1,\
    "RENALCHRONIC": 2,\
    "TABACCO": 2,\
    "CLASIFFICATION_FINAL": 5\
}'

curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: application
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) unmatched close brace/bracket in URL position 297:
DATE_DIED: 05/06/2020,     INTUBED: 97,     PNEUMONIA: 2,     AGE: 55,     PREGNANT: 2,     DIABETES: 1,     COPD: 2,     ASTHMA: 2,     INMSUPR: 2,     HIPERTENSION: 1,     OTHER_DISEASE: 2,     CARDIOVASCULAR: 2,     OBESITY: 1,     RENALCHRONIC: 2,     TABACCO: 2,     CLASIFFICATION_FINAL: 5 }'